- name: General tasks
  hosts: servers
  become: yes
  gather_facts: no
  tasks:
    - name: Ping test
      ping:

- name: Execute dependencies playbook
  gather_facts: no
  hosts: dependencies
  become: yes
  tasks:
    - include_role:
        name: dependencies

- name: branectl_compile
  gather_facts: no
  hosts: branectl_compile
  become: yes
  tasks:
    - include_role:
        name: branectl_compile


- name: Execute worker playbook
  gather_facts: no
  hosts: worker_node
  become: no
  tasks:
    - include_role:
        name: worker_node


- name: Execute central playbook
  gather_facts: no
  hosts: central_node
  become: no
  tasks:
    - include_role:
        name: central_node



- name: check for issues with docker containers 
  gather_facts: no
  hosts: retrive_logs
  become: yes
  tasks:
    - include_role:
        name: retrive_logs


- name: send Certs 
  gather_facts: no
  hosts: Move_certs
  become: no
  tasks:
    - include_role:
        name: Move_certs

