---
## check if image is built
# brane-api.tar  brane-drv.tar  brane-plr.tar  brane-prx.tar
- name: check if file exists
  stat:
    path: ./brane/target/release/brane-plr.tar
  register: stat_result


- name:  compile brane central instance
  command: python3 ./make.py instance
  args:                                                                     
    chdir: "./brane"
  register: result1
  when: not stat_result.stat.exists


## move to correct folder 


- name:  generate infra 
  command: branectl generate infra -f -p ./config/infra.yml {{LOCATION_ID}}:{{ FAKE_HOSTNAME_WORKER }}

- name:  generate proxy 
  command: branectl generate proxy -f -p ./config/proxy.yml

- name: generate node 
  command: branectl generate node -f -H {{FAKE_HOSTNAME_CENTRAL}}:{{HOSTNAME_CENTRAL}} central {{FAKE_HOSTNAME_CENTRAL}}


#change to non static path
- name: 
  file:
    path: /home/{{hostvars['server1']['ansible_user']}}/config/certs/{{ LOCATION_ID }}
    state: directory
    mode: '0755'


- name: Copy worker certificate from localhost
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/client_cert/ca.pem"
    dest: "/home/{{hostvars['server1']['ansible_user']}}/config/certs/{{ LOCATION_ID }}/"



- name: start central node
  command: branectl start --image-dir "./brane/target/release" central


- name: Wait for Brane central node to start
  shell: |
    docker logs brane-api 2>&1 | grep "Now serving"
  register: output
  until: output.stdout != ""
  retries: 40
  delay: 5
  when: Wait_for_brane_start is true