---
# - name: copy ca cert to remote 
#   ansible.netcommon.net_put:
#     src: client_cert/ca.pem
#     protocol: sftp
#     dest: "{{ C_Remote }}:{{ C_Remote_dest }}"


# - name: copy client-id cert to remote 
#   ansible.netcommon.net_put:
#     src: client_cert/client-id.pem
#     protocol: sftp
#     dest: "{{ C_Remote }}:{{ C_Remote_dest }}"

- debug: msg="sftp {{ C_Remote }}:{{ C_Remote_dest }} <<< $'put {{ playbook_dir }}/client_cert/ca.pem' "

- name: test
  command: "sftp {{ C_Remote }}:{{ C_Remote_dest }} <<< $'put {{ playbook_dir }}/client_cert/ca.pem' "
  register: Result_1
  ignore_errors: true

- debug: msg="{{Result_1.stderr}}"

- debug: msg="{{Result_1.stdout}}"